### ISSUE TITLE
日記タイトル作成ページの作成

### ISSUE THREAD

**Issue by kogoro06** [kogoro06/my_song_journal#51]
以下のように修正したTODOを提案します：

---

## 概要

日記作成を開始するための最初のページとして、タイトルのみを設定できるページを作成します。

### パス
- `/journals/new`

### ゴール
- ユーザーが日記のタイトルを設定し、日記詳細作成ページ `/journals/:journal_id/articles/new` に進めるようにする。

---

## TODO

- [x] `/journals/new` のルーティングを作成し、日記タイトル作成ページが表示されるようにする。
- [x] タイトル入力フォームを追加。
- [x] タイトルを保存後、日記詳細作成ページ `/journals/:journal_id/articles/new` に遷移するよう設定する。
- [x] タイトルが未入力の場合にエラーメッセージが表示されるようにする。
- [x] 日記詳細作成ページへ遷移するボタンが正しく動作することを確認する。
- [x] UI デザインを調整し、使いやすい見た目に仕上げる。

---

## 要件

- `/journals/new` にタイトル入力フォームが表示されること。
- タイトルを入力し、保存後に `/journals/:journal_id/articles/new` に遷移すること。
- 入力が失敗した場合にエラーメッセージが表示されること。
- 日記詳細作成ページへの遷移ボタンが正しく動作すること。

---
